#!/usr/bin/env bash
# ─── Tau Terminal — Cross-Terminal Throughput Benchmark ───
#
# Compares real-world throughput by running `cat` on a generated test file
# in every available terminal emulator on the system.
#
# Each terminal is launched via its CLI (or osascript for macOS Terminal.app),
# runs `time cat <testfile>`, and captures the wall-clock duration.
#
# Usage:
#   chmod +x bench/cross-terminal.sh
#   bash bench/cross-terminal.sh
#
# Prerequisites:
#   - Test files generated by bench/generate-data.sh (run first)
#   - Terminals installed at their standard paths

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
DATA_DIR="$PROJECT_ROOT/bench/data"
RESULTS_FILE="$PROJECT_ROOT/bench/results.txt"

# ─── Colors ───
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

# ─── Test Data Generation ───

generate_data() {
  mkdir -p "$DATA_DIR"

  echo -e "${BOLD}Generating test data...${NC}"

  # cat-sim: 10MB of mostly plain text with few escapes
  if [ ! -f "$DATA_DIR/cat_10mb.txt" ]; then
    echo "  → cat_10mb.txt (10 MB, plain text)"
    node -e "
      const fs = require('fs');
      const path = require('path');
      let out = '';
      const target = 10 * 1024 * 1024;
      while (out.length < target) {
        let line = '';
        const len = 20 + Math.floor(Math.random() * 100);
        for (let i = 0; i < len && out.length < target; i++) {
          if (Math.random() < 0.02) {
            line += '\x1b[3' + Math.floor(Math.random() * 8) + 'm';
          }
          line += String.fromCharCode(32 + Math.floor(Math.random() * 95));
        }
        out += line + '\n';
      }
      fs.writeFileSync(path.join('$DATA_DIR', 'cat_10mb.txt'), out);
    "
  fi

  # compiler-sim: 10MB of ANSI-heavy output
  if [ ! -f "$DATA_DIR/compiler_10mb.txt" ]; then
    echo "  → compiler_10mb.txt (10 MB, ANSI-heavy)"
    node -e "
      const fs = require('fs');
      const path = require('path');
      const styles = [
        '\x1b[31m','\x1b[32m','\x1b[33m','\x1b[34m','\x1b[35m','\x1b[36m',
        '\x1b[1m','\x1b[3m','\x1b[4m','\x1b[0m',
        '\x1b[38;5;196m','\x1b[48;5;22m',
        '\x1b[38;2;255;128;0m','\x1b[H','\x1b[2J','\x1b[K',
      ];
      let out = '';
      const target = 10 * 1024 * 1024;
      while (out.length < target) {
        let line = '';
        const len = 20 + Math.floor(Math.random() * 100);
        for (let i = 0; i < len && out.length < target; i++) {
          if (Math.random() < 0.5) {
            line += styles[Math.floor(Math.random() * styles.length)];
          }
          line += String.fromCharCode(32 + Math.floor(Math.random() * 95));
        }
        out += line + '\n';
      }
      fs.writeFileSync(path.join('$DATA_DIR', 'compiler_10mb.txt'), out);
    "
  fi

  # large-file: 50MB of mixed content
  if [ ! -f "$DATA_DIR/large_50mb.txt" ]; then
    echo "  → large_50mb.txt (50 MB, mixed)"
    node -e "
      const fs = require('fs');
      const path = require('path');
      const styles = [
        '\x1b[31m','\x1b[32m','\x1b[33m','\x1b[0m',
        '\x1b[38;5;196m','\x1b[48;5;22m',
        '\x1b[1m','\x1b[4m',
      ];
      let out = '';
      const target = 50 * 1024 * 1024;
      while (out.length < target) {
        let line = '';
        const len = 20 + Math.floor(Math.random() * 100);
        for (let i = 0; i < len && out.length < target; i++) {
          if (Math.random() < 0.2) {
            line += styles[Math.floor(Math.random() * styles.length)];
          }
          line += String.fromCharCode(32 + Math.floor(Math.random() * 95));
        }
        out += line + '\n';
      }
      fs.writeFileSync(path.join('$DATA_DIR', 'large_50mb.txt'), out);
    "
  fi

  echo -e "  ${GREEN}Done.${NC}"
}

# ─── Benchmark Helpers ───

# Run a timed cat command in a given terminal.
# $1: display name
# $2: command to launch terminal with the cat command
# $3: test file path
# $4: description
bench_terminal() {
  local name="$1"
  local launch_cmd="$2"
  local testfile="$3"
  local desc="$4"

  echo -ne "  ${CYAN}${name}${NC} (${desc})... "

  local start=$(date +%s%3N)

  # Run the command with a timeout (60s for 10MB, 120s for 50MB)
  local timeout_sec=60
  if [[ "$desc" == *"50MB"* ]]; then
    timeout_sec=120
  fi

  if timeout $timeout_sec bash -c "$launch_cmd" > /dev/null 2>&1; then
    local end=$(date +%s%3N)
    local elapsed=$((end - start))
    printf "${GREEN}%6d ms${NC}\n" $elapsed
    echo "$name|$desc|$elapsed|success" >> "$RESULTS_FILE"
  else
    local rc=$?
    if [ $rc -eq 124 ]; then
      echo -e "${RED}TIMEOUT${NC}"
      echo "$name|$desc|timeout|timeout" >> "$RESULTS_FILE"
    else
      echo -e "${RED}FAILED (rc=$rc)${NC}"
      echo "$name|$desc|failed|error" >> "$RESULTS_FILE"
    fi
  fi
}

# ─── Terminal Detection ───

detect_and_bench() {
  local testfile="$1"
  local desc="$2"
  local filepath="$DATA_DIR/$testfile"

  if [ ! -f "$filepath" ]; then
    echo -e "  ${RED}File not found: $filepath${NC}"
    return
  fi

  echo ""
  echo -e "${BOLD}─── $desc ───${NC}"

  echo -e "  ${YELLOW}Note: Tau renderer coverage lives in bench:renderer; this script compares external terminals and headless parser throughput.${NC}"

  # xterm.js parser (headless, Node.js)
  bench_terminal "xterm.js (parser)" \
    "cd '$PROJECT_ROOT' && node --expose-gc -e \"
      const fs = require('fs');
      const data = fs.readFileSync('$filepath');
      import('@xterm/xterm').then(({Terminal}) => {
        const t = new Terminal({cols:120, rows:40, allowProposedApi:true});
        t.write(data.toString(), () => {});
        t.dispose();
      });
    \"" \
    "$testfile" "$desc"

  # Ghostty (native terminal)
  if command -v ghostty &> /dev/null; then
    bench_terminal "ghostty (native)" \
      "ghostty -e 'bash -c \"time cat $filepath > /dev/null; sleep 0.5\"'" \
      "$testfile" "$desc"
  else
    echo -e "  ${YELLOW}ghostty: not found, skipping${NC}"
    echo "ghostty (native)|$desc|n/a|not_installed" >> "$RESULTS_FILE"
  fi

  # VS Code integrated terminal
  if command -v code &> /dev/null; then
    bench_terminal "vscode (xterm.js)" \
      "code --wait --new-window --disable-extensions '$filepath' && sleep 0.5" \
      "$testfile" "$desc"
  else
    echo -e "  ${YELLOW}vscode: not found, skipping${NC}"
    echo "vscode (xterm.js)|$desc|n/a|not_installed" >> "$RESULTS_FILE"
  fi

  # macOS Terminal.app (via osascript)
  bench_terminal "Terminal.app" \
    "osascript -e '
      tell application \"Terminal\"
        activate
        do script \"time cat $filepath > /dev/null; exit\"
        delay 0.5
        repeat
          if not (exists window 1) then exit repeat
          delay 0.1
        end repeat
      end tell
    '" \
    "$testfile" "$desc"

  # iTerm2 (if installed)
  if [ -d "/Applications/iTerm.app" ]; then
    bench_terminal "iTerm2" \
      "osascript -e '
        tell application \"iTerm2\"
          activate
          tell current session of current window
            write text \"time cat $filepath > /dev/null; exit\"
          end tell
          delay 0.5
        end tell
      '" \
      "$testfile" "$desc"
  else
    echo -e "  ${YELLOW}iTerm2: not installed, skipping${NC}"
    echo "iTerm2|$desc|n/a|not_installed" >> "$RESULTS_FILE"
  fi

  # Superset
  if [ -d "/Applications/Superset.app" ]; then
    bench_terminal "superset (xterm.js)" \
      "open -a Superset --args --run-command 'time cat $filepath > /dev/null' 2>/dev/null || true" \
      "$testfile" "$desc"
  else
    echo -e "  ${YELLOW}superset: not installed, skipping${NC}"
    echo "superset (xterm.js)|$desc|n/a|not_installed" >> "$RESULTS_FILE"
  fi
}

# ─── Main ───

main() {
  echo -e "${BOLD}╔══════════════════════════════════════════════════════╗${NC}"
  echo -e "${BOLD}║   Tau — Cross-Terminal Throughput Benchmark         ║${NC}"
  echo -e "${BOLD}╚══════════════════════════════════════════════════════╝${NC}"
  echo ""

  # Generate test data
  generate_data

  # Reset results
  echo "terminal|test|duration_ms|status" > "$RESULTS_FILE"

  # Warm up: run a small test to ensure terminals are responsive
  echo -e "${BOLD}Warming up...${NC}"
  echo "placeholder" > "$DATA_DIR/warmup.txt"

  # ── Run benchmarks ──
  detect_and_bench "cat_10mb.txt" "cat 10MB (plain)"
  detect_and_bench "compiler_10mb.txt" "compiler 10MB (ANSI-heavy)"
  detect_and_bench "large_50mb.txt" "large 50MB (mixed)"

  # ── Print Results ──
  echo ""
  echo -e "${BOLD}╔══════════════════════════════════════════════════════╗${NC}"
  echo -e "${BOLD}║                   RESULTS                           ║${NC}"
  echo -e "${BOLD}╚══════════════════════════════════════════════════════╝${NC}"
  echo ""

  if [ -f "$RESULTS_FILE" ]; then
    echo -e "${BOLD}Terminal                      Test                  Time${NC}"
    echo -e "${BOLD}────────────────────────      ────────────────      ────${NC}"

    # Parse and display results
    tail -n +2 "$RESULTS_FILE" | while IFS='|' read -r term test dur status; do
      if [ "$status" = "success" ]; then
        printf "%-28s %-24s ${GREEN}%6s ms${NC}\n" "$term" "$test" "$dur"
      elif [ "$status" = "timeout" ]; then
        printf "%-28s %-24s ${RED}%6s${NC}\n" "$term" "$test" "TIMEOUT"
      elif [ "$status" = "not_installed" ]; then
        printf "%-28s %-24s ${YELLOW}%6s${NC}\n" "$term" "$test" "n/a"
      else
        printf "%-28s %-24s ${RED}%6s${NC}\n" "$term" "$test" "FAILED"
      fi
    done
  fi

  echo ""
  echo -e "${BOLD}Results saved to:${NC} $RESULTS_FILE"
  echo -e "${BOLD}Parser-only benchmark:${NC} bun run bench"
  echo ""
  echo -e "${YELLOW}Note: 'parser' entries measure VT parse time only (no rendering).${NC}"
  echo -e "${YELLOW}Full-terminal entries include rendering + IPC + compositing overhead.${NC}"
}

main "$@"
